"""record sort keys

Revision ID: 38fcc92ef161
Revises: 554b31010233
Create Date: 2025-11-17 11:03:08.432043

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38fcc92ef161"
down_revision: Union[str, Sequence[str], None] = "554b31010233"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("sk_artist_year", sa.String(), nullable=False))
    op.add_column("records", sa.Column("sk_artist_title", sa.String(), nullable=False))
    op.add_column(
        "records", sa.Column("sk_label_year_artist", sa.String(), nullable=False)
    )
    op.add_column(
        "records", sa.Column("sk_label_artist_year", sa.String(), nullable=False)
    )
    op.create_index(
        op.f("ix_records_sk_artist_title"), "records", ["sk_artist_title"], unique=False
    )
    op.create_index(
        op.f("ix_records_sk_artist_year"), "records", ["sk_artist_year"], unique=False
    )
    op.create_index(
        op.f("ix_records_sk_label_artist_year"),
        "records",
        ["sk_label_artist_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_records_sk_label_year_artist"),
        "records",
        ["sk_label_year_artist"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_records_sk_label_year_artist"), table_name="records")
    op.drop_index(op.f("ix_records_sk_label_artist_year"), table_name="records")
    op.drop_index(op.f("ix_records_sk_artist_year"), table_name="records")
    op.drop_index(op.f("ix_records_sk_artist_title"), table_name="records")
    op.drop_column("records", "sk_label_artist_year")
    op.drop_column("records", "sk_label_year_artist")
    op.drop_column("records", "sk_artist_title")
    op.drop_column("records", "sk_artist_year")
    # ### end Alembic commands ###
