"""artist.discogs_id

Revision ID: 42b73b63b20d
Revises: 38fcc92ef161
Create Date: 2026-01-08 12:44:01.946483

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from src.modules.records.models import RecordData, RecordDataType

# revision identifiers, used by Alembic.
revision: str = "42b73b63b20d"
down_revision: Union[str, Sequence[str], None] = "38fcc92ef161"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("artists", sa.Column("discogs_id", sa.String(), nullable=True))
    op.alter_column(
        "records",
        "data",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=RecordDataType(RecordData),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "records",
        "data",
        existing_type=RecordDataType(RecordData),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("artists", "discogs_id")
    # ### end Alembic commands ###
