"""create records tables

Revision ID: 554b31010233
Revises: 085b0f9c8f04
Create Date: 2025-10-29 10:23:56.680822

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "554b31010233"
down_revision: Union[str, Sequence[str], None] = "085b0f9c8f04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("year_release", sa.Integer(), nullable=False),
        sa.Column("year_pressing", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_records_title"), "records", ["title"], unique=False)
    op.create_index(
        op.f("ix_records_year_pressing"), "records", ["year_pressing"], unique=False
    )
    op.create_index(
        op.f("ix_records_year_release"), "records", ["year_release"], unique=False
    )
    op.create_table(
        "records_artists",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("artist_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("record_id", "artist_id"),
    )
    op.create_table(
        "records_labels",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["labels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
        ),
        sa.PrimaryKeyConstraint("record_id", "label_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("records_labels")
    op.drop_table("records_artists")
    op.drop_index(op.f("ix_records_year_release"), table_name="records")
    op.drop_index(op.f("ix_records_year_pressing"), table_name="records")
    op.drop_index(op.f("ix_records_title"), table_name="records")
    op.drop_table("records")
    # ### end Alembic commands ###
