"""artist.integrations

Revision ID: a583df16771f
Revises: 42b73b63b20d
Create Date: 2026-03-04 15:45:17.145707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.shared.types import Integrations, JSONBType


# revision identifiers, used by Alembic.
revision: str = "a583df16771f"
down_revision: Union[str, Sequence[str], None] = "42b73b63b20d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artists",
        sa.Column("integrations", JSONBType(Integrations), nullable=True),
    )
    op.drop_column("artists", "discogs_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artists",
        sa.Column("discogs_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("artists", "integrations")
    # ### end Alembic commands ###
